/////////////////////////////////////////////////
// A party supplemental data div on Add XX page.
//
// @file:   PartySupplementalDiv.js
// @author: Xiaosiqi Yang <yang4131@umn.edu>
/////////////////////////////////////////////////

var React = require('react');
var OwnershipOption = require('./OwnershipOption');
var IndustryOption = require('../quotes/create-quote/SalesChannelOption');
var AccountPartyOption = require('../quotes/create-quote/AccountPartyOption');
var CommonStore = require('../../stores/CommonStore');
var CommonActions = require('../../actions/CommonActions');

var PartySupplementalDiv = React.createClass({

    getInitialState: function () {
        return {
            ownershipsObjArray: [],
            salesChannelsObjArray: [],
            accountPartiesObjArray: []
        };
    },

    componentDidMount: function () {
        CommonStore.addGetAllOwnershipsListener(this._onGetOwnerships);
        CommonActions.getOwnerships();
        CommonStore.addGetSalesChannelsListener(this._onGetSalesChannels);
        CommonActions.getSalesChannels();
        CommonStore.addGetAccountPartiesListener(this._onGetAccountParties);
        CommonActions.getAccountParties();
    },

    componentWillUnmount: function() {
        CommonStore.removeListener('getAllOwnerships', this._onGetOwnerships);
        CommonStore.removeListener('getSalesChannels', this._onGetSalesChannels);
        CommonStore.removeListener('getAccountParties', this._onGetAccountParties);
    },

    _onGetOwnerships: function () {
        this.setState({
            ownershipsObjArray: CommonStore.getOwnershipsObjArray()
        });
    },

    _onGetSalesChannels: function () {
        this.setState({
            salesChannelsObjArray: CommonStore.getSalesChannelsObjArray()
        });
    },

    _onGetAccountParties: function () {
        this.setState({
            accountPartiesObjArray: CommonStore.getAccountPartiesObjArray()
        });
    },

    render: function () {
        /* jshint ignore:start */

        // make OwnershipEnumId drop-down menu  -- these are the rows generated by query:
        var ownerships = this.state.ownershipsObjArray;
        var ownershipsJSX = [];
        var noOwnership = { party_id: null };
        ownershipsJSX.push(<OwnershipOption key={ 'ownership_' } ownership={ noOwnership }/>);
        for (var i = 0; i < ownerships.length; i++) {
            ownershipsJSX.push(<OwnershipOption key={ 'ownership_' + i } ownership={ ownerships[i] }/>);
        }

        var salesChannels = this.state.salesChannelsObjArray;
        var salesChannelsJSX = [];
        var noSalesChannel = { party_id: null };
        salesChannelsJSX.push(<IndustryOption key={ 'salesChannel_' } salesChannel={ noSalesChannel }/>);
        for (var i = 0; i < salesChannels.length; i++) {
            salesChannelsJSX.push(<IndustryOption key={ 'salesChannel_' + i } salesChannel={ salesChannels[i] }/>);
        }

        var accountParties = this.state.accountPartiesObjArray;
        var accountPartiesJSX = [];
        var noAccountParty = { party_id: null };
        accountPartiesJSX.push(<AccountPartyOption key={ 'accountParty_' } accountParty={ noAccountParty }/>);
        for (var i = 0; i < accountParties.length; i++) {
            accountPartiesJSX.push(<AccountPartyOption key={ 'accountParty_' + i } accountParty={ accountParties[i] }/>);
        }

        return (
            <div>
                <div className="row">
                    <div className="col-xs-12">
                        <h2>Party Supplemental Info </h2>
                    </div>
                </div>

                <div className="row">

                    {/*
                    <div className="col-lg-6 col-xs-12">
                        <div className="form-group">
                            <label htmlFor="parentPartyId">Parent Account * </label>
                            <div className="input-group">
                                <div className="input-group-addon"><i className="fa fa-file-text-o" aria-hidden="true"></i></div>
                                <input type="text" className="form-control" id="parentPartyId" placeholder="Parent Account, there is no default" required data-error="Required, integer (up to 11 digits)" onChange={ this.props.onChange } />
                            </div>
                            <div className="help-block with-errors"></div>
                        </div>
                    </div>
                    */}


                    <div className="col-lg-6 col-xs-12">
                        <div className="form-group">
                            <label htmlFor="parentPartyId">Parent Account</label>
                            <div className="input-group">
                                <div className="input-group-addon"><i className="fa fa-bars" aria-hidden="true"></i></div>
                                <select
                                    className="form-control"
                                    id="parentPartyId"
                                    onChange={ this.props.onChange }
                                    value={ this.props.ent.parentPartyId } >
                                        { accountPartiesJSX }
                                </select>
                            </div>
                        </div>
                    </div>

                    <div className="col-lg-6 col-xs-12">
                        <div className="form-group">
                            <label htmlFor="companyName">Company Name</label>
                            <div className="input-group">
                                <div className="input-group-addon"><i className="fa fa-file-text-o" aria-hidden="true"></i></div>
                                <input type="text" className="form-control" id="companyName" placeholder="Company Name"
                                pattern="^[\x20-\x7E\u00C0-\u00FC]{1,100}$"
                                data-error="Max length 100 characters"
                                onChange={ this.props.onChange } value={ this.props.ent.companyName} />
                            </div>
                            {/* The next line will display error messages. See http://1000hz.github.io/bootstrap-validator/ */}
                            <div className="help-block with-errors"></div>
                        </div>
                    </div>
                </div>

                <div className="row">
                    <div className="col-lg-6 col-xs-12">
                        <div className="form-group">
                            <label htmlFor="annualRevenue">Annual revenue (required)</label>
                            <div className="input-group">
                                <div className="input-group-addon"><i className="fa fa-money" aria-hidden="true"></i></div>
                                <input type="number" className="form-control" id="annualRevenue" placeholder="Annual revenue" onChange={ this.props.onChange } value={ this.props.ent.annualRevenue} />
                            </div>
                            <div className="help-block with-errors"></div>
                        </div>
                    </div>
                    <div className="col-lg-6 col-xs-12">
                        <div className="form-group">
                            <label htmlFor="numEmployees">Number of Employees (required)</label>
                            <div className="input-group">
                                <div className="input-group-addon"><i className="fa fa-file-text-o" aria-hidden="true"></i></div>
                                <input type="number" className="form-control" id="numEmployees" placeholder="Number of Employees" onChange={ this.props.onChange } value={ this.props.ent.numEmployees} />
                            </div>
                        </div>
                    </div>
                </div>

                <div className="row">
                    <div className="col-lg-6 col-xs-12">
                        <div className="form-group">
                            <label htmlFor="industryEnumId">Industry</label>
                            <div className="input-group">
                                <div className="input-group-addon"><i className="fa fa-industry" aria-hidden="true"></i></div>
                                <select id="industryEnumId" className="form-control" onChange={ this.props.onChange } value={ this.props.ent.industry} >
                                    {salesChannelsJSX}
                                </select>
                            </div>
                        </div>
                    </div>
                    <div className="col-lg-6 col-xs-12">
                        <div className="form-group">
                            <label htmlFor="ownershipEnumId">Ownership</label>
                            <div className="input-group">
                                <div className="input-group-addon"><i className="fa fa-usd" aria-hidden="true"></i></div>
                                <select id="ownershipEnumId" className="form-control" onChange={ this.props.onChange } value={ this.props.ent.ownership} >
                                    {ownershipsJSX}
                                </select>
                            </div>
                        </div>
                    </div>
                </div>


                <div className="row">
                    <div className="col-lg-6 col-xs-12">
                        <div className="form-group">
                            <label htmlFor="tickerSymbol">Ticker Symbol</label>
                            <div className="input-group">
                                <div className="input-group-addon"><i className="fa fa-file-text-o" aria-hidden="true"></i></div>
                                <input id="tickerSymbol" type="text" className="form-control" placeholder="Type a Ticker Symbol" onChange={ this.props.onChange } value={ this.props.ent.tickerSymbol}/>
                            </div>
                        </div>
                    </div>
                    <div className="col-lg-6 col-xs-12">
                        <div className="form-group">
                            <label htmlFor="importantNote" >Important Note</label>
                            <div className="input-group">
                                <div className="input-group-addon"><i className="fa fa-file-text-o" aria-hidden="true"></i></div>
                                <textarea id="importantNote" className="form-control" rows="4" placeholder="Note" onChange={ this.props.onChange } value={ this.props.ent.importantNote} ></textarea>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        );
        /* jshint ignore:end */
    }

});

module.exports = PartySupplementalDiv;